# Introduction to Tensors

In [2]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.20.0


In [3]:
# Create tensors with tensorflow
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of the tensor
scalar.ndim

0

In [6]:
# Creeate a Vector
vector = tf.constant([10, 10])
vector.ndim

1

In [7]:
# create a matrix 
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)

another_matrix.ndim

2

In [10]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>